sudo: required
services:
  - docker
 
before_install:
  - docker build -t mikebaoc/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run mikebaoc/react-test npm test -- --coverage
 
after_success:
  - docker build -t mikebaoc/multi-client ./client
  - docker build -t mikebaoc/multi-nginx ./nginx
  - docker build -t mikebaoc/multi-server ./server
  - docker build -t mikebaoc/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take all these build images to docker hub
  - docker push mikebaoc/multi-client
  - docker push mikebaoc/multi-nginx
  - docker push mikebaoc/multi-server
  - docker push mikebaoc/multi-worker





















